import { WallpaperConfig } from '../types';
import { getPaletteById } from './palettes';

export const PRESET_WALLPAPERS: WallpaperConfig[] = [
  {
    id: 'preset-aura-sunset',
    title: '暮光弥散 (Aura Sunset Glow)',
    style: 'aura',
    paletteId: 'aura-sunset',
    colors: [...getPaletteById('aura-sunset').colors],
    gradientType: 'radial',
    angle: 135,
    scale: 1.15,
    complexity: 4,
    blur: 45,
    noiseIntensity: 18,
    contrast: 105,
    brightness: 102,
    saturation: 110,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: -5 },
    shapeType: 'circle',
    showShadows: false,
    strokeWidth: 0,
    strokeColor: '#FFFFFF',
    hasTypography: false,
    seed: 101,
  },
  {
    id: 'preset-bauhaus-modern',
    title: '构成主义 (Bauhaus Composition)',
    style: 'bauhaus',
    paletteId: 'bauhaus-primary',
    colors: [...getPaletteById('bauhaus-primary').colors],
    gradientType: 'linear',
    angle: 45,
    scale: 1.0,
    complexity: 5,
    blur: 0,
    noiseIntensity: 12,
    contrast: 100,
    brightness: 100,
    saturation: 100,
    blendMode: 'multiply',
    elementOffset: { x: 10, y: -10 },
    shapeType: 'polygon',
    showShadows: true,
    strokeWidth: 3,
    strokeColor: '#18181B',
    hasTypography: true,
    typographyText: 'BAUHAUS',
    typographySubtext: 'FORM FOLLOWS FUNCTION',
    typographyPosition: 'bottom-left',
    seed: 202,
  },
  {
    id: 'preset-japanese-zen',
    title: '静谧日轮 (Zen Sun & Ripples)',
    style: 'japanese-zen',
    paletteId: 'terracotta-dune',
    colors: [...getPaletteById('terracotta-dune').colors],
    gradientType: 'linear',
    angle: 90,
    scale: 1.0,
    complexity: 6,
    blur: 2,
    noiseIntensity: 16,
    contrast: 102,
    brightness: 98,
    saturation: 95,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: -15 },
    shapeType: 'circle',
    showShadows: false,
    strokeWidth: 1.5,
    strokeColor: '#C87D55',
    hasTypography: false,
    seed: 303,
  },
  {
    id: 'preset-nordic-arch',
    title: '北欧拱门与悬浮球体 (Nordic Portal)',
    style: 'nordic-arch',
    paletteId: 'matcha-oat',
    colors: [...getPaletteById('matcha-oat').colors],
    gradientType: 'linear',
    angle: 180,
    scale: 0.95,
    complexity: 3,
    blur: 0,
    noiseIntensity: 14,
    contrast: 105,
    brightness: 100,
    saturation: 90,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: 5 },
    shapeType: 'arch',
    showShadows: true,
    strokeWidth: 0,
    strokeColor: '#FFFFFF',
    hasTypography: false,
    seed: 404,
  },
  {
    id: 'preset-topo-contours',
    title: '沙丘等高线 (Desert Contours)',
    style: 'topo-contours',
    paletteId: 'desert-eclipse',
    colors: [...getPaletteById('desert-eclipse').colors],
    gradientType: 'linear',
    angle: 60,
    scale: 1.2,
    complexity: 8,
    blur: 0,
    noiseIntensity: 20,
    contrast: 110,
    brightness: 95,
    saturation: 105,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: 0 },
    shapeType: 'contour',
    showShadows: false,
    strokeWidth: 2,
    strokeColor: '#F59E0B',
    hasTypography: false,
    seed: 505,
  },
  {
    id: 'preset-prismatic',
    title: '棱镜折光 (Prismatic Angles)',
    style: 'prismatic-angle',
    paletteId: 'deep-space',
    colors: [...getPaletteById('deep-space').colors],
    gradientType: 'conic',
    angle: 210,
    scale: 1.05,
    complexity: 6,
    blur: 8,
    noiseIntensity: 15,
    contrast: 115,
    brightness: 95,
    saturation: 120,
    blendMode: 'source-over',
    elementOffset: { x: 5, y: -5 },
    shapeType: 'polygon',
    showShadows: true,
    strokeWidth: 0,
    strokeColor: '#FFFFFF',
    hasTypography: false,
    seed: 606,
  },
  {
    id: 'preset-zen-monolith',
    title: '原石静寂 (Zen Monolith Balance)',
    style: 'zen-monolith',
    paletteId: 'mono-silver',
    colors: [...getPaletteById('mono-silver').colors],
    gradientType: 'linear',
    angle: 180,
    scale: 1.0,
    complexity: 3,
    blur: 0,
    noiseIntensity: 22,
    contrast: 110,
    brightness: 98,
    saturation: 0,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: 0 },
    shapeType: 'polygon',
    showShadows: true,
    strokeWidth: 0,
    strokeColor: '#FFFFFF',
    hasTypography: false,
    seed: 707,
  },
  {
    id: 'preset-flow-waves',
    title: '碧波流体 (Ethereal Flow Waves)',
    style: 'flow-waves',
    paletteId: 'aegean-breeze',
    colors: [...getPaletteById('aegean-breeze').colors],
    gradientType: 'linear',
    angle: 120,
    scale: 1.1,
    complexity: 5,
    blur: 4,
    noiseIntensity: 14,
    contrast: 105,
    brightness: 100,
    saturation: 110,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: 10 },
    shapeType: 'wave',
    showShadows: true,
    strokeWidth: 1,
    strokeColor: 'rgba(255,255,255,0.4)',
    hasTypography: false,
    seed: 808,
  },
  {
    id: 'preset-cyber-grid',
    title: '地平线网格 (Horizon Cyber Grid)',
    style: 'cyber-grid',
    paletteId: 'tokyo-neon',
    colors: [...getPaletteById('tokyo-neon').colors],
    gradientType: 'linear',
    angle: 0,
    scale: 1.0,
    complexity: 7,
    blur: 0,
    noiseIntensity: 18,
    contrast: 120,
    brightness: 95,
    saturation: 130,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: 0 },
    shapeType: 'grid',
    showShadows: false,
    strokeWidth: 1.5,
    strokeColor: '#00F0FF',
    hasTypography: false,
    seed: 909,
  },
  {
    id: 'preset-color-field',
    title: '纯色场域 (Rothko Color Fields)',
    style: 'color-field',
    paletteId: 'kyoto-mist',
    colors: [...getPaletteById('kyoto-mist').colors],
    gradientType: 'linear',
    angle: 90,
    scale: 1.0,
    complexity: 4,
    blur: 25,
    noiseIntensity: 25,
    contrast: 100,
    brightness: 100,
    saturation: 90,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: 0 },
    shapeType: 'polygon',
    showShadows: false,
    strokeWidth: 0,
    strokeColor: '#FFFFFF',
    hasTypography: false,
    seed: 1010,
  },
  {
    id: 'preset-lavender-aura',
    title: '薰衣草夜想 (Lavender Dream)',
    style: 'aura',
    paletteId: 'lavender-solitude',
    colors: [...getPaletteById('lavender-solitude').colors],
    gradientType: 'radial',
    angle: 45,
    scale: 1.25,
    complexity: 5,
    blur: 50,
    noiseIntensity: 16,
    contrast: 108,
    brightness: 100,
    saturation: 115,
    blendMode: 'source-over',
    elementOffset: { x: -10, y: 10 },
    shapeType: 'circle',
    showShadows: false,
    strokeWidth: 0,
    strokeColor: '#FFFFFF',
    hasTypography: false,
    seed: 1111,
  },
  {
    id: 'preset-obsidian-gold',
    title: '黑曜金流 (Obsidian Gold Horizon)',
    style: 'japanese-zen',
    paletteId: 'obsidian-gold',
    colors: [...getPaletteById('obsidian-gold').colors],
    gradientType: 'linear',
    angle: 15,
    scale: 1.0,
    complexity: 4,
    blur: 0,
    noiseIntensity: 20,
    contrast: 120,
    brightness: 95,
    saturation: 110,
    blendMode: 'source-over',
    elementOffset: { x: 0, y: -5 },
    shapeType: 'circle',
    showShadows: true,
    strokeWidth: 2,
    strokeColor: '#D4AF37',
    hasTypography: false,
    seed: 1212,
  },
];
